### PR TITLE
Create christmas song - bass notes.txt

### PR DESCRIPTION
**Pull request by francoiscilliers**
Added Christmas Song's bass notes

### CODE REVIEW

**Comment by kebijih** [comment]
@francoiscilliers are we still doing this song?

**Comment by francoiscilliers** [comment]
No idea. I'll check with wozza01

**Comment by francoiscilliers** [comment]
Confirmed. No Christmas song. That was 3hours well spent

**Comment by kebijih** [comment]
Hahahahaha, oh well.

**Pull request closed without merging**
